### PR TITLE
ZEA-2391: module based __main__

### PR DESCRIPTION
**Pull request by pan93412**
## Usage

This PR adds the support for this project structure:

```
/<name>/__init__.py
/<name>/__main__.py
```

For this project, we run it with:

```
python3 -m <name>
```

You should configure your build system in `pyproject.toml`:

```
[project]
name = "testmodule"
version = "0.1.0"
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
```

And add your project directory in `requirements.txt`:

```
# add your project here
-e .

# and your dependencies
numpy==1.23.4
```

## How do this work

We first install the dependencies (without the `-e .`) to maximally leverage the Docker layer cache:

```
sed '/-e/d' requirements.txt | pip install -r /dev/stdin
```

After copying the project files, we rerun `requirements.txt` to run `-e .`

```
pip install -r requirements.txt
```

### CODE REVIEW

**Comment by yuaanlin** [comment]
Could you provide an example of an open-source project that follows this format? Is this project structure common within the Python ecosystem?

**Comment by pan93412** [comment]
> Could you provide an example of an open-source project that follows this format? Is this project structure common within the Python ecosystem?

Pretty easy to find these examples, since it has been a modern Pip packaging standard. [It is also a documented behavior](https://docs.python.org/3/library/__main__.html).

https://github.com/python-poetry/poetry/blob/master/src/poetry/__main__.py
https://github.com/pypa/pip/blob/main/src/pip/__main__.py

**Comment by yuaanlin** [comment]
> Pretty easy to find these examples, since it has been a modern Pip packaging standard. [It is also a documented behavior](https://docs.python.org/3/library/__main__.html).
> 
> https://github.com/python-poetry/poetry/blob/master/src/poetry/__main__.py https://github.com/pypa/pip/blob/main/src/pip/__main__.py

The two repositories you've provided are not likely to be candidates for anyone looking to use zbpack to build them into a  running service.

**Comment by pan93412** [comment]
> > Pretty easy to find these examples, since it has been a modern Pip packaging standard. [It is also a documented behavior](https://docs.python.org/3/library/__main__.html).
> > [python-poetry/poetry@`master`/src/poetry/__main__.py](https://github.com/python-poetry/poetry/blob/master/src/poetry/__main__.py?rgh-link-date=2024-01-14T09%3A26%3A20Z) [pypa/pip@`main`/src/pip/__main__.py](https://github.com/pypa/pip/blob/main/src/pip/__main__.py?rgh-link-date=2024-01-14T09%3A26%3A20Z)
> 
> The two repositories you've provided are not likely to be candidates for anyone looking to use zbpack to build them into a running service.

Well. Why I implemented this function is allowing me deploying my backend project on Zeabur, which make use of `__main__.py`:

CleanShot 2024-01-14 at 17 28 10@2x

Such hierarchy is common in projects that are initialized with Rye and PDM, which is the default hierarchy using the `init` command.

```
tree
.
├── README.md
├── __pycache__
├── pyproject.toml
├── src
│   └── example_package
│       ├── __init__.py
│       └── __pycache__
└── tests
    ├── __init__.py
    └── __pycache__

7 directories, 4 files
```

I don't see a reason to disallow such usage when it is a pattern that some people indeed use.

**Comment by yuaanlin** [comment]
I would greatly appreciate it if you could take another look at this PR to ensure that it won't impact any Python projects currently utilizing zbpack, regardless of the package manager being used or any serverless situation.

If your PR is ready for review, please change the status from draft to open.

**Pull request closed without merging**
