### PR TITLE
Created CODE_OF_CONDUCT.md

### LINKED ISSUE #69: add code of conduct
Hi there!
I recommend adding a CODE_OF_CONDUCT.md file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

I would like to work on this issue. Please assign it to me under GSSoC'23.

Thank you!

### PR DESCRIPTION
**Pull request by S-ishita**
closes #69

### CODE REVIEW

**Comment by pan93412** [comment]
You need to rebase your `main` branch to our latest commit, as well as rewrite your commit message to match our requirement.

To rebase your branch and rewrite your message in one step, run:

```bash
git rebase -i origin/main
```

**Comment by S-ishita** [comment]
Is it ok now @pan93412

**Comment by pan93412** [comment]
Not really – you have not fixed up your commit message yet. I can help you correct that if you authorize me to do that.

**Comment by S-ishita** [comment]
Yeah sure

**Pull request merged**
