### PR TITLE
refactor: plan and packer

### PR DESCRIPTION
**Pull request by aFlyBird0**
## Summary

extract two main interface:

```Go
// Packer can identify the plan type and generate a Dockerfile.
type Packer interface {
	plan.Identifier
	GenerateDockerfile(types.PlanMeta) (string, error)
}

// Identifier identifies the plan type and how to get the plan meta.
type Identifier interface {
	PlanType() types.PlanType
	Match(afero.Fs) bool
	PlanMeta(NewPlannerOptions) types.PlanMeta
}
```

In that case, all type definitions are located within the pkg package. The internal package contains implementations of the internal interfaces defined in pkg.

If you need to add a new deployment type in the future, you would simply create a new package within internal and add the implemented types for the supported systems in pkg/zeaburpack/identifiers.go and pkg/zeaburpack/packers.go.

## Test

image

image

### CODE REVIEW

**Comment by aFlyBird0** [comment]
golangci-lint fixed: 
image

**Comment by pan93412** [comment]
```
You have commit messages with warnings

⧗   input: ci: fix golangci-lint errors
⚠   subject must be sentence-case, start-case [subject-case]

⚠   found 0 problems, 1 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

⧗   input: refactor: plan and packer
⚠   subject must be sentence-case, start-case [subject-case]

⚠   found 0 problems, 1 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

`git rebase -i origin/main` your commits?

**Review by pan93412 — APPROVED** [review]

**Comment by pan93412** [comment]
Besides, it is not a CI-related error; it should be started with `refactor`

[ci: fix golangci-lint errors](https://github.com/zeabur/zbpack/pull/59/commits/88797cc66f2af935091cbb2e05dec20917bdb822)

**Comment by aFlyBird0** [comment]
> ```
> You have commit messages with warnings
> 
> ⧗   input: ci: fix golangci-lint errors
> ⚠   subject must be sentence-case, start-case [subject-case]
> 
> ⚠   found 0 problems, 1 warnings
> ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
> 
> ⧗   input: refactor: plan and packer
> ⚠   subject must be sentence-case, start-case [subject-case]
> 
> ⚠   found 0 problems, 1 warnings
> ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
> ```
> 
> `git rebase -i origin/main` your commits?

done

**Comment by aFlyBird0** [comment]
> Besides, it is not a CI-related error; it should be started with `style` or `refactor`:
> 
> [ci: fix golangci-lint errors](https://github.com/zeabur/zbpack/pull/59/commits/88797cc66f2af935091cbb2e05dec20917bdb822)

Got it, thank you!

**Comment by pan93412** [comment]
```
You have commit messages with warnings

⧗   input: refactor: plan and packer
⚠   subject must be sentence-case, start-case [subject-case]

⚠   found 0 problems, 1 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

**Review by pan93412 — APPROVED** [review]

**Comment by pan93412** [comment]
cc @yuaanlin merge

**Pull request merged**
